name: poxlyfe
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52984
title: "Paco's Reads"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e48270'
    - '#c76a5c'
    - '#eff0f5'
    - '#9e4737'
    - '#c0abad'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
