name: poxlyfe
favicon: null
layout_spectrum: 0.44135186541825533
typography_spectrum: 0.9380562636069953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09821970365010202
  lightness: 0.7718807472847402
  saturation: 0.33196176611818373
  rhythmicContrast: 0.028136831475421786
purpose: []
