name: poxlyfe
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52984
title: "Paco's Reads"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5f5f5f'
    - '#000000'
    - '#92a5c4'
    - '#f5f632'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
