name: poxlyfe
favicon: null
layout_spectrum: 0.75448
typography_spectrum: 0.9380562636069953
title: "Paco's Reads"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1d1f'
    - '#005a43'
    - '#d5f6ff'
    - '#7c0018'
    - '#8c7c5c'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
