name: poxlyfe
favicon: null
layout_spectrum: 0.5774
typography_spectrum: 0.52984
title: "Paco's Reads"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#19100d'
    - '#765f45'
    - '#e4c6c3'
    - '#ab0000'
    - '#0097bd'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
