name: poxlyfe
favicon: null
layout_spectrum: 0.66459
typography_spectrum: 0.52984
title: "Paco's Reads"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121512'
    - '#c4c4c2'
    - '#ffffff'
    - '#606165'
    - '#86817e'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
